### ISSUE TITLE
Panel broken in atom-material-ui theme

### ISSUE THREAD

**Issue by bennypowers** [Galooshi/atom-import-js#40]
The atom material ui theme has this style

```css
/* /Users/bennyp/.atom/packages/atom-material-ui/index.less */
.overlay, atom-panel.modal {
    color: rgba(221, 221, 221, 0.65);
    background-color: #212121;
    font-size: 12px;
    padding: 10px;
    box-shadow: 0 0 10px transparent;
    border-radius: 0.125rem;
    overflow: hidden;
    box-shadow: 0 0.625rem 1.25rem rgba(0, 0, 0, 0.19), 0 0.375rem 0.375rem rgba(0, 0, 0, 0.23);
}
```

which sets overflow: hidden on the dropdown.

anyone coming here with this problem can add this to their stylesheet to fix it
```less
.theme-atom-material-ui {
  .overlay, atom-panel.modal {
    overflow: initial;
  }
}
```
